# Generated by Django 4.2.1 on 2023-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
