# Generated by Django 4.2.1 on 2023-05-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_pets_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('D', 'Domestico'), ('W', 'Silvestre')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pet')),
            ],
        ),
    ]
