# Generated by Django 4.2.1 on 2023-05-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_specie_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.specie'),
            preserve_default=False,
        ),
    ]
